#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    # uncomment the following line and replace it with your discovery URL
    # discovery: https://discovery.etcd.io/c421b0de60799f5a1dd63f6a90615808
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    # give etcd more time if it's under heavy load - prevent leader election thrashing
    peer-election-timeout: 2000
    # heartbeat interval should ideally be 1/4 or 1/5 of peer election timeout
    peer-heartbeat-interval: 500
  fleet:
    # We have to set the public_ip here so this works on Vagrant -- otherwise, Vagrant VMs
    # will all publish the same private IP. This is harmless for cloud providers.
    public-ip: $private_ipv4
    # allow etcd to slow down at times
    etcd_request_timeout: 3
  units:
  - name: format-ephemeral.service
    command: start
    content: |
      [Unit]
      Description=Formats the ephemeral drive
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/sbin/wipefs -f /dev/sdc
      ExecStart=/usr/sbin/mkfs.btrfs -f /dev/sdc
  - name: var-lib-docker.mount
    command: start
    content: |
      [Unit]
      Description=Mount ephemeral to /var/lib/docker
      Requires=format-ephemeral.service
      After=format-ephemeral.service
      Before=docker.service
      [Mount]
      What=/dev/sdc
      Where=/var/lib/docker
      Type=btrfs

  - name: 10-weave.network
    runtime: false
    content: |
      [Match]
      Type=bridge
      Name=weave*
      [Network]

  - name: weave.service
    content: |
      [Unit]
      After=install-weave.service
      Description=Weave Network
      Documentation=http://zettio.github.io/weave/
      Requires=install-weave.service
      [Service]
      EnvironmentFile=/etc/weave.%H.env
      ExecStartPre=/opt/bin/weave launch $WEAVE_PEERS
      ExecStartPre=/opt/bin/weave launch-dns $WEAVEDNS_ADDR
      ExecStart=/usr/bin/docker attach weave
      Restart=on-failure
      ExecStop=/opt/bin/weave stop
      ExecStop=/opt/bin/weave stop-dns

  - name: install-weave.service
    command: start
    enable: true
    content: |
      [Unit]
      After=network-online.target
      After=docker.service
      Description=Install Weave
      Documentation=http://zettio.github.io/weave/
      Requires=network-online.target
      Requires=docker.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/docker pull zettio/weave:latest
      ExecStartPre=/usr/bin/docker pull zettio/weavedns:latest
      ExecStartPre=/usr/bin/docker pull zettio/weavetools:latest
      ExecStartPre=/usr/bin/wget -N -P /opt/bin \
          https://raw.github.com/zettio/weave/master/weave
      #ExecStartPre=/bin/ln -s /etc/weave.%H.env /etc/weave.env
      ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
      ExecStart=/bin/echo Weave Installed

  - name: weave-network.target
    command: start
    enable: true
    content: |
      [Unit]
      Requires=weave.service
      RefuseManualStart=no
      Wants=weave.service
      [Install]
      WantedBy=multi-user.target
