#!/bin/sh -x
set -e

[ `id -u` = 0 ] || {
    echo "weave must be run as 'root'" >&2
    exit 1

[ $# -eq 2 ] || {
    echo "Usage:"
    echo "weave-helper <container_interface>"
    exit 1
}

set +e

container_interface="${1:-'eth0'}"

docker events | while read event
do
        echo $event | grep -q -v '\ start$' && continue

        with_container_id=`echo $event | sed 's/.*Z\ \(.*\):\ .*/\1/'`

        only_if="test -n '{{ .NetworkSettings.IPAddress }}'"
        in_namespace="nsenter -n -t {{ .State.Pid }} --"
        ethtool_tx_off="ethtool -K ${container_interface} tx off >/dev/null"

        command_template="${only_if} && { (${in_namespace} ${ethtool_tx_off}); }"

        eval `docker inspect --format="${command_template}" ${with_container_id}`
done
