# -*- mode: ruby -*-
# vi: set ft=ruby :

$num_instances = 1
$instance_name_prefix = 'marathon'

Vagrant.configure(2) do |config|
  config.vm.box = 'chef/centos-7.0'

  (1..$num_instances).each do |i|
    config.vm.define vm_name = '%s-%02d' % [$instance_name_prefix, i] do |config|

      config.vm.network :private_network, ip: '172.16.0.6'

      config.vm.provision :shell, inline: <<-SHELL
        hostnamectl set-hostname #{vm_name}
        echo 172.16.0.6 #{vm_name} >> /etc/hosts
      SHELL

      # Disable automatic box update checking. If you disable this, then
      # boxes will only be checked for updates when the user runs
      # `vagrant box outdated`. This is not recommended.
      # config.vm.box_check_update = false

      # Create a forwarded port mapping which allows access to a specific port
      # within the machine from a port on the host machine. In the example below,
      # accessing "localhost:8080" will access port 80 on the guest machine.
      # config.vm.network "forwarded_port", guest: 80, host: 8080

      config.vm.provider :virtualbox do |vb|
        vb.gui = false
        # vb.check_guest_additions = false
        # vb.functional_vboxsf = false

        vb.memory = 1024*6
        vb.cpus = 2
      end

      config.vm.provision :shell, inline: <<-SHELL
        rpm -i http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
        yum -q -y install mesos-0.22.1 marathon-0.8.2 mesosphere-zookeeper-3.4.6 docker

        systemctl -q start zookeeper.service
        sleep 5
        cp -a /vagrant/mesos-slave.service.d /etc/systemd/system/
        systemctl -q start mesos-master.service mesos-slave.service marathon.service
      SHELL

      config.vm.provision :shell, inline: <<-SHELL
        cd /vagrant
        cp weave /usr/local/bin/
        cp weave.target weave.service weavedns.service weaveproxy.service /etc/systemd/system/

        /usr/local/bin/weave setup

        systemctl -q start weave.service weaveproxy.service
      SHELL
    end
  end
end
