# -*- mode: ruby -*-
# vi: set ft=ruby :

$mesos_slaves = (ENV['MESOS_SLAVES'] || 1).to_i

$network = [172, 17, 85]

Vagrant.configure(2) do |config|
  config.vm.box = 'chef/centos-7.0'

  vms = (0..$mesos_slaves).map{ |a| "mesos-%02d" % [a] }

  ips = {}

  vms.each_with_index{ |i, x| ips[i] = ($network + [x+100]).join('.') }

  vms.each_with_index do |i, x|

    config.vm.define vm_name = i do |config|

      config.vm.network :private_network, ip: ips[vm_name]

      config.vm.provision :shell, inline: <<-SHELL
        hostnamectl set-hostname #{vm_name}
        echo #{ips[vm_name]} #{vm_name} >> /etc/hosts
      SHELL

      # Disable automatic box update checking. If you disable this, then
      # boxes will only be checked for updates when the user runs
      # `vagrant box outdated`. This is not recommended.
      # config.vm.box_check_update = false

      # Create a forwarded port mapping which allows access to a specific port
      # within the machine from a port on the host machine. In the example below,
      # accessing "localhost:8080" will access port 80 on the guest machine.
      # config.vm.network "forwarded_port", guest: 80, host: 8080

      config.vm.provider :virtualbox do |vb|
        vb.gui = false
        # vb.check_guest_additions = false
        # vb.functional_vboxsf = false

        vb.memory = 1024*2
        vb.cpus = 2
      end

      config.vm.provision :shell, inline: 'yum -q -y install docker'

      ## Compile a list of IP addresses module one for this VM
      weave_peers = ips.select{|host, addr| addr if host != vm_name}.values
      config.vm.provision :shell, inline: <<-SHELL
        /vagrant/install_weave.sh
        /vagrant/setup_and_launch_weave.sh #{weave_peers.join(' ')}
      SHELL

      if x == 0
        config.vm.provision :shell, inline: <<-SHELL
          /vagrant/install_mesosphere_packages.sh
          /vagrant/launch_mesos_master_services.sh
        SHELL
      elsif x > 0
         config.vm.provision :shell, inline: <<-SHELL
           /vagrant/install_mesosphere_packages.sh
           /vagrant/setup_and_launch_mesos_slave.sh zk://#{ips['mesos-00']}:2181/mesos
         SHELL
      end
    end
  end
end
